name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.4
        uses: actions/setup-java@v2
        with:
          java-version: '1.4'
          distribution: 'adopt'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
